# Generated by Django 5.1.4 on 2025-01-14 09:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='weight',
            constraint=models.UniqueConstraint(fields=('user', 'created_at'), name='unique_weight_user_created_at'),
        ),
    ]
