# Production version

services:
  pg:
    image: ${ECR_REGISTRY}/macroseat-postgres:latest
    build:
      context: ..
      dockerfile: ./docker/pg/Dockerfile.prod
      args:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        PGPORT: ${PGPORT}
    container_name: pg
    volumes:
      - ../db_data:/var/lib/postgresql/data:cached
    networks:
      - service-network

  redis:
    image: redis:7.4.2
    container_name: redis
    networks:
      - service-network

  django-server:
    image: ${ECR_REGISTRY}/macroseat-django:latest
    build:
      context: ..
      dockerfile: ./docker/django/Dockerfile.prod
    container_name: django-server
    command: sh /app/docker/scripts/run_django_prod.sh
    working_dir: /app
    environment:
      - ENV=prod
    volumes:
      - ../log:/app/log
    networks:
      - service-network
    links:
      - pg
      - redis
    depends_on:
      - pg
    expose:
      - 8000

  nginx:
    image: ${ECR_REGISTRY}/macroseat-nginx:latest
    build:
      context: .. # relative position to docker-compose.yml file location
      dockerfile: ./docker/nginx/Dockerfile.prod
    volumes:
      - ../log/nginx:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    networks:
      - service-network
    depends_on:
      - django-server

networks:
  service-network:
    name: "service-network"
    driver: bridge
