# Production version

services:
  pg:
    image: postgres:16
    container_name: pg
    volumes:
      - ../db_data:/var/lib/postgresql/data:cached
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGPORT=${POSTGRES_PORT}
    networks:
      - service-network

  redis:
    image: redis:7.4.2
    container_name: redis
    networks:
      - service-network

  django-server:
    image: macroseat-app
    build:
      context: .. # relative position to docker-compose.yml file location
      dockerfile: ./docker/django/Dockerfile.prod
    container_name: django-server
    command: sh /app/docker/scripts/run_django_prod.sh
    working_dir: /app
    environment:
      - ENV=prod
    volumes:
      - ../log:/app/log
    networks:
      - service-network
    links:
      - pg
      - redis
    depends_on:
      - pg
    expose:
      - 8000

  nginx:
    image: nginx:alpine
    volumes:
      - ../nginx_conf/nginx_prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ../log/nginx:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    networks:
      - service-network
    depends_on:
      - django-server

networks:
  service-network:
    name: "service-network"
    driver: bridge
