FROM postgres:16

# Set work directory
WORKDIR /

COPY docker/db-init-scripts/ docker-entrypoint-initdb.d/
COPY docker/scripts/create_db.sql create_db.sql
ARG POSTGRES_PASSWORD
ARG PGPORT


RUN echo "Password during build: ${POSTGRES_PASSWORD}"
RUN echo "Port during build: ${PGPORT}"


ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD
ENV PGPORT=$PGPORT