FROM postgres:16

# Switch to root to install packages
USER root

# Install pgroonga packages
RUN apt-get update
RUN apt-get install lsb-release
RUN apt install -y -V ca-certificates lsb-release wget
RUN wget https://apache.jfrog.io/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
RUN apt install -y -V ./apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
RUN wget https://packages.groonga.org/debian/groonga-apt-source-latest-$(lsb_release --codename --short).deb
RUN apt install -y -V ./groonga-apt-source-latest-$(lsb_release --codename --short).deb
RUN apt update
RUN apt install -y -V postgresql-16-pgdg-pgroonga
RUN rm -rf /var/lib/apt/lists/*

# Switch back to postgres user
USER postgres