# Generated by Django 5.1.4 on 2025-01-09 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.TextField(choices=[('general_user', 'general_user'), ('nutritionist', 'nutritionist')])),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8)),
                ('first_login', models.BooleanField(default=True)),
                ('habit', models.IntegerField(blank=True, null=True)),
                ('target', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
