# Generated by Django 5.1.4 on 2025-01-09 04:17

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('authen', '0001_initial'),  # Put the last migration of auth app here
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE UNIQUE INDEX auth_user_email_idx ON auth_user (email);',
            reverse_sql='DROP INDEX auth_user_email_idx;'
        ),
    ]
