# Generated by Django 5.1.4 on 2025-01-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_add_index_on_auth_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='sex',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
