# Generated by Django 5.1.4 on 2025-01-12 02:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('user', 'created_at'), name='unique_user_created_at'),
        ),
    ]
