# Use Python image
FROM python:3.13

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set work directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip3 install -r requirements.txt

# Copy project
COPY . .

EXPOSE 8000

RUN chmod +x /app/docker/scripts/run_django_dev.sh

#ENTRYPOINT ["/app/entrypoint.sh"]