# Generated by Django 5.1.4 on 2025-01-13 07:34

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS pgroonga;",
            reverse_sql="DROP EXTENSION IF EXISTS pgroonga;"
        ),
        migrations.RunSQL(
            sql="""
            CREATE INDEX pgroonga_food_name_index ON food_food USING pgroonga (food_name);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS pgroonga_food_name_index;
            """
        ),
    ]
