# Generated by Django 5.1.4 on 2025-01-14 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS pg_trgm;",
            reverse_sql="DROP EXTENSION IF EXISTS pg_trgm;"
        ),
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS btree_gin;",
            reverse_sql="DROP EXTENSION IF EXISTS btree_gin;"
        ),
        migrations.RunSQL(
            sql='''
            CREATE INDEX food_name_uppercase_gin_idx
            ON food_food USING gin (upper(food_name) gin_trgm_ops);
            ''',
            reverse_sql='DROP INDEX food_name_uppercase_gin_idx;'
        ),
    ]
